name: CleanLauncher
description: A No-Distraction Android Launcher.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  device_apps: ^1.0.9
  shared_preferences: ">=0.5.7+3 <2.0.0"
  alphabet_list_scroll_view: ^1.0.6
  mobx: ^0.3.8
  flutter_mobx: ^0.3.3
  flutter_svg: ^0.17.1
  flutter_slidable: "^0.5.4"
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/feather.svg
    - assets/feather_black.svg
