name: CleanLauncher
description: A No-Distraction Android Launcher.

publish_to: "none"

version: 1.1.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mobx: ^0.3.8
  device_apps: ^1.0.9
  flutter_mobx: ^0.3.3
  flutter_svg: ^0.17.1
  android_intent: ^0.3.7+3
  flutter_slidable: ^0.5.4
  alphabet_list_scroll_view: ^1.0.6
  shared_preferences: ">=0.5.7+3 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app-logo-dark.png
    - assets/app-logo-light.png
